# Generated by Django 3.1.1 on 2020-09-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200915_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='back_or_not',
            field=models.TextField(default='hoge$#@#$', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.TextField(default='hoge$#@#$', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='number',
            field=models.TextField(default='hoge$#@#$', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.TextField(default='hoge$#@#$', null=True),
        ),
    ]
