# Generated by Django 3.1.1 on 2020-09-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200915_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sum',
            field=models.IntegerField(null=True),
        ),
    ]
